FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ["nicho ingles/rodgerkoller/site/", "/usr/share/nginx/html/"]
COPY ["nicho ingles/rodgerkoller/site/nginx.conf", "/etc/nginx/conf.d/default.conf"]
RUN rm -f /usr/share/nginx/html/Dockerfile /usr/share/nginx/html/nginx.conf /usr/share/nginx/html/netlify.toml && rm -rf /usr/share/nginx/html/.netlify
EXPOSE 80
